// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _42_DemoCrudAppUsingEntityFw.DAL;

#nullable disable

namespace _42_DemoCrudAppUsingEntityFw.Migrations
{
    [DbContext(typeof(Vdbcontext))]
    partial class VdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_42_DemoCrudAppUsingEntityFw.Models.Vehicle", b =>
                {
                    b.Property<int?>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Vid"));

                    b.Property<string>("Vmodel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("mfgdate")
                        .HasColumnType("date");

                    b.Property<double?>("vprice")
                        .HasColumnType("float");

                    b.HasKey("Vid");

                    b.ToTable("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
